# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.7.0"
gem "rubocop-github", "~> 0.16.2"
gem "rubocop-performance", "~> 1.8.0"
gem "rubocop-rails", "~> 2.8", ">= 2.8.0"
gem "rubocop-rspec", "~> 2.5.0"
